server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
  sql:
    init:
      platform: mysql
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


jwt:
  secret-key: {JWT_KEY}

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
